#pragma config(Sensor, in1,    lift,           sensorPotentiometer)
#pragma config(Sensor, in2,    claw,           sensorPotentiometer)
#pragma config(Sensor, in8,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  liftLimit,      sensorTouch)
#pragma config(Motor,  port1,           rightDrive,    tmotorVex393HighSpeed_HBridge, openLoop, reversed, driveRight)
#pragma config(Motor,  port2,           rightDrive2,   tmotorVex393HighSpeed_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port3,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightLift2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftLift,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           leftLift2,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           rightLift,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           claw2,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           leftDrive2,    tmotorVex393HighSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port10,          leftDrive,     tmotorVex393HighSpeed_HBridge, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



//GLOBAL VARIABLES
int liftCount;
int clawCount;
int limitSwitch;
int rightDriveCount;
int leftDriveCount;


//AUTONOMOUS VARIABLES
int autoHolder;


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#include "Methods.c"
#include "BareLiftingTask.c"
#include "BareDriveTask.c"
#include "BareLCDTask.c"
#include "Auto_Right_Center.c"
#include "Auto_Left_Center.c"
#include "Auto_Right_3stars.c"
#include "Auto_Left_3stars.c"
#include "Auto_Right_OneSide.c"
#include "Auto_Left_OneSide.c"



/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	clearLCDLine(0);
	clearLCDLine(1);
	startTask(autonomousLCD);

	//SET UP ALL SENSORS
	SensorType[in1] = sensorNone;
	SensorType[in2] = sensorNone;
	SensorType[in8] = sensorNone;
	wait1Msec(1000);
	SensorType[in1] = sensorPotentiometer;
	SensorType[in2] = sensorPotentiometer;
	SensorType[in8] = sensorGyro;


	SensorValue[in1] = 0;
	SensorValue[in2] = 0;
	SensorValue[in8] = 0;
	wait1Msec(2000);

	SensorScale[in8] = 260;
	SensorFullCount[in8] = 3600;


	//set up encoders
	SensorValue(rightEncoder) = 0;
	SensorValue(leftEncoder) = 0;

}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	stopTask(autonomousLCD);

	if(autoHolder == 0){
		startTask(right_center);
	}
	else if(autoHolder == 1){
		startTask(left_center);
	}
	else if(autoHolder == 2){
		startTask(right_3stars);
	}
	else if(autoHolder == 3){
		startTask(left_3stars);
	}
	else if(autoHolder == 4){
		startTask(Right_OneSide);
	}
	else if(autoHolder == 5){
		startTask(Left_OneSide);
	}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{

	startTask(drive);
	startTask(lifting);
	startTask(clawSpeedTask);
	while (true)
	{
		liftCount = SensorValue(lift);

		clawCount = SensorValue(claw);

		limitSwitch = SensorValue(liftLimit);

		rightDriveCount = SensorValue(rightEncoder);

		leftDriveCount = SensorValue(leftEncoder);
	}

}
